In [56]:
import numpy as np
import sys

In [14]:
np.array([1, 2, 3, 4])


array([1, 2, 3, 4])

In [16]:
a = np.array([1, 2, 3, 4])


In [18]:
b = np.array([0, .5, 1, 1.5, 2])


In [20]:
a[0], a[1]


(1, 2)

In [22]:
a[0:]


array([1, 2, 3, 4])

In [24]:
a[1:3]


array([2, 3])

In [26]:
a[1:-1]


array([2, 3])

In [28]:
a[::2]


array([1, 3])

In [30]:
b


array([0. , 0.5, 1. , 1.5, 2. ])

In [32]:
b[0], b[2], b[-1]

(0.0, 1.0, 2.0)

In [34]:
b[[0, 2, -1]]


array([0., 1., 2.])

In [36]:
a


array([1, 2, 3, 4])

In [38]:
a.dtype


dtype('int32')

In [40]:
b


array([0. , 0.5, 1. , 1.5, 2. ])

In [42]:
b.dtype


dtype('float64')

In [46]:
np.array([1, 2, 3, 4], dtype=np.float16)


array([1., 2., 3., 4.], dtype=float16)

In [48]:
np.array([1, 2, 3, 4], dtype=np.int8)


array([1, 2, 3, 4], dtype=int8)

In [50]:
c = np.array(['a', 'b', 'c'])


In [52]:
c.dtype


dtype('<U1')

In [64]:
d = np.array([{'a': 1}, sys])
d

array([{'a': 1}, <module 'sys' (built-in)>], dtype=object)

In [66]:
d.dtype

dtype('O')

In [68]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])


In [70]:
A.shape


(2, 3)

In [72]:
A.ndim


2

In [74]:
A.size


6

In [80]:
B = np.array([
    [
        [12, 11, 10],
        [9, 8, 7],
    ],
    [
        [6, 5, 4],
        [3, 2, 1]
    ]
])
B

array([[[12, 11, 10],
        [ 9,  8,  7]],

       [[ 6,  5,  4],
        [ 3,  2,  1]]])

In [82]:
B.shape


(2, 2, 3)

In [84]:
B.ndim


3

In [86]:
B.size


12

In [96]:
A = np.array([
#.   0. 1. 2
    [1, 2, 3], # 0
    [4, 5, 6], # 1
    [7, 8, 9]  # 2
])

In [98]:
A[1]

array([4, 5, 6])

In [100]:
A[1][0]


4

In [102]:
A[1, 0]


4

In [104]:
A[0:2]


array([[1, 2, 3],
       [4, 5, 6]])

In [106]:
A[:, :2]


array([[1, 2],
       [4, 5],
       [7, 8]])

In [108]:
A[:2, :2]


array([[1, 2],
       [4, 5]])

In [110]:
A[:2, 2:]


array([[3],
       [6]])

In [114]:
A[1] = np.array([10, 10, 10])
A


array([[ 1,  2,  3],
       [10, 10, 10],
       [ 7,  8,  9]])

In [118]:
A[2] = 99
A

array([[ 1,  2,  3],
       [10, 10, 10],
       [99, 99, 99]])

In [120]:
a = np.array([1, 2, 3, 4])


In [122]:
a.sum()


10

In [124]:
a.mean()


2.5

In [126]:
a.std()


1.118033988749895

In [128]:
a.var()


1.25

In [130]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [132]:
A.sum()


45

In [134]:
A.mean()


5.0

In [136]:
A.std()


2.581988897471611

In [138]:
A.sum(axis=0)


array([12, 15, 18])

In [140]:
A.sum(axis=1)


array([ 6, 15, 24])

In [142]:
A.mean(axis=0)


array([4., 5., 6.])

In [144]:
A.mean(axis=1)


array([2., 5., 8.])

In [146]:
A.std(axis=0)


array([2.44948974, 2.44948974, 2.44948974])

In [148]:
A.std(axis=1)


array([0.81649658, 0.81649658, 0.81649658])

In [164]:
a = np.arange(4)
a

array([0, 1, 2, 3])

In [166]:
a + 10

array([10, 11, 12, 13])

In [168]:
a * 10

array([ 0, 10, 20, 30])

In [172]:
a+=100
a

array([200, 201, 202, 203])

In [174]:
l = [0, 1, 2, 3]


In [176]:
[i * 10 for i in l]


[0, 10, 20, 30]

In [180]:
a = np.arange(4)
a

array([0, 1, 2, 3])

In [184]:
b = np.array([10, 10, 10, 10])
b

array([10, 10, 10, 10])

In [186]:
a + b


array([10, 11, 12, 13])

In [188]:
a * b


array([ 0, 10, 20, 30])

In [192]:
a = np.arange(4)
a

array([0, 1, 2, 3])

In [194]:
a[0], a[-1]


(0, 3)

In [196]:
a[[0, -1]]


array([0, 3])

In [198]:
a[[True, False, False, True]]


array([0, 3])

In [200]:
a >= 2


array([False, False,  True,  True])

In [202]:
a[a >= 2]


array([2, 3])

In [204]:
a[a > a.mean()]


array([2, 3])

In [206]:
a[~(a > a.mean())]


array([0, 1])

In [208]:
a[(a == 0) | (a == 1)]

array([0, 1])

In [210]:
a[(a <= 2) & (a % 2 == 0)]


array([0, 2])

In [214]:
A = np.random.randint(100, size=(3, 3))
A

array([[30, 47,  6],
       [24,  7, 76],
       [ 5, 30,  8]])

In [216]:
A

array([[30, 47,  6],
       [24,  7, 76],
       [ 5, 30,  8]])

In [218]:
A[np.array([
    [True, False, True],
    [False, True, False],
    [True, False, True]
])]

array([30,  6,  7,  5,  8])

In [220]:
A > 30


array([[False,  True, False],
       [False, False,  True],
       [False, False, False]])

In [222]:
A[A > 30]


array([47, 76])

In [224]:

A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [226]:
B = np.array([
    [6, 5],
    [4, 3],
    [2, 1]
])

In [228]:
A.dot(B)


array([[20, 14],
       [56, 41],
       [92, 68]])

In [230]:
B.T

array([[6, 4, 2],
       [5, 3, 1]])

In [234]:
sys.getsizeof(1)

28

In [236]:
sys.getsizeof(10**100)


72

In [238]:
np.dtype(int).itemsize


4

In [240]:
np.dtype(np.int8).itemsize

1

In [242]:
np.dtype(float).itemsize

8

In [244]:
sys.getsizeof([1])

64

In [246]:
np.array([1]).nbytes

4

In [248]:
l = list(range(100000))

In [250]:
a = np.arange(100000)


In [252]:
%time np.sum(a ** 2)


CPU times: total: 0 ns
Wall time: 1e+03 μs


216474736

In [254]:
%time sum([x ** 2 for x in l])


CPU times: total: 0 ns
Wall time: 12 ms


333328333350000

In [256]:
np.random.random(4)

array([0.45114989, 0.93351476, 0.2438486 , 0.61207276])

In [258]:
np.random.random(size=4)

array([0.57193984, 0.68260766, 0.594736  , 0.52688276])

In [260]:
np.random.random((4,4))

array([[0.0826457 , 0.36039034, 0.39622425, 0.82652634],
       [0.76788973, 0.73579134, 0.54902443, 0.76393681],
       [0.02113793, 0.36352255, 0.96918453, 0.21464254],
       [0.86008284, 0.3254355 , 0.18175326, 0.66944102]])

In [262]:
np.random.rand(4)

array([0.15176972, 0.85745011, 0.90290115, 0.02477611])

In [264]:
np.random.randn(3,2)

array([[-0.08631666,  1.18407673],
       [-1.55107666, -0.03543403],
       [ 1.17823526, -0.61193314]])

In [266]:
np.random.randint(2,7,8)

array([4, 5, 6, 6, 4, 4, 4, 3])

In [268]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [270]:
np.arange(0,1,0.05)

array([0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ,
       0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95])

In [272]:
np.zeros(4)

array([0., 0., 0., 0.])

In [274]:
np.zeros((2,2,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [278]:
np.ones((1,1,4))

array([[[1., 1., 1., 1.]]])

In [280]:
np.empty((1,2,3))

array([[[0.08631666, 1.18407673, 1.55107666],
        [0.03543403, 1.17823526, 0.61193314]]])

In [282]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [284]:
np.eye(3,5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.]])

In [286]:
np.eye(8, 4, k=1)


array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [288]:
np.linspace(0, 1, 20)


array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [290]:
np.identity(3)


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [292]:
np.empty((2, 2))


array([[1.39067116e-309, 8.28904606e-317],
       [0.00000000e+000, 0.00000000e+000]])

In [294]:
np.arange(10).reshape(5, 2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [296]:
np.ones([2,2], dtype=np.int8)


array([[1, 1],
       [1, 1]], dtype=int8)

In [298]:
np.ones([3,2], dtype=np.float64)


array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [302]:
X = np.arange(4, dtype=np.int8)
X

array([0, 1, 2, 3], dtype=int8)

In [304]:
np.ones_like(X)


array([1, 1, 1, 1], dtype=int8)

In [308]:
np.ones([4,4], dtype=np.int16) * 5

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]], dtype=int16)

In [310]:
np.identity(3)


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [328]:
np.random.randint(10, size=3)

array([7, 7, 9])

In [340]:
np.random.random((3,3,3)) 
# np.random.randn(3,3,3)

array([[[0.21391071, 0.29181602, 0.52702402],
        [0.46635613, 0.62866495, 0.27939471],
        [0.62928745, 0.37116267, 0.58973548]],

       [[0.61064163, 0.55110121, 0.92508748],
        [0.42618859, 0.53727003, 0.24122851],
        [0.35758632, 0.73826319, 0.00878169]],

       [[0.53120601, 0.24090731, 0.72640163],
        [0.2200498 , 0.91406961, 0.70111076],
        [0.20013016, 0.79241228, 0.57353471]]])

In [342]:
#np.random.random((3,3,3)) 
np.random.randn(3,3,3)

array([[[ 6.85408570e-01, -2.02357234e-01, -2.21445014e-01],
        [ 3.24464018e-01, -1.46193110e+00,  7.03776162e-01],
        [-1.44964935e+00, -4.43518384e-01,  3.83801787e-01]],

       [[-2.05492346e+00, -7.87008332e-01,  4.88397017e-01],
        [ 2.34144805e-02, -6.01648078e-01, -1.00873865e-01],
        [ 2.40728230e-02,  1.35624266e+00, -2.61626563e-03]],

       [[-3.27028503e+00, -6.33775984e-01,  3.96225765e-01],
        [-2.41805136e-01, -3.53708108e-01, -4.43210470e-01],
        [ 1.04647949e-01, -3.55304415e-01,  2.80490464e-01]]])

In [346]:
X = np.array([5,2,3], dtype=np.int8)
print(X, id(X))

Y = np.copy(X)
print(Y, id(Y))

[5 2 3] 2898842956496
[5 2 3] 2898842956976


In [348]:

X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

#X[:2][:2] wrong!
#X[0:2, 0:2]
X[:2, :2]

array([[1, 2],
       [5, 6]])

In [350]:
X = [0, 10, -5, 40, -3]

X.sort()
X

[-5, -3, 0, 10, 40]